### ISSUE TITLE
/etc/nix/nix.conf cannot already exist when running this script

### ISSUE THREAD

**Issue by a1russell** [aherrmann/nix-multi-user-install#2]
I know the `configure_nix()` function will prompt to overwrite `/etc/nix/nix.conf`, but that's too late in the process. Because `/nix/chroot_builds/static_bash`, specified in `build-chroot-dirs`, doesn't exist at a time it's needed, an error is produced, and the install script fails. Currently the only way to get things working is to manually delete `/etc/nix/nix.conf`.

I suggest finding out where in the process things crash, changing the script to rename `/etc/nix/nix.conf` to something else beforehand, and then restoring the file afterwards if it did exist.

**Comment by aherrmann** [comment]
@a1russell Thanks for catching that.

I hope it works now. I'm getting build failures for bash right now due to a mismatching hash for one of the patches (NixOS/nixpkgs#11512). So, it's difficult to test.
